Send node instances
netdata/aclk-schemas pull request #2
Opened 2021-03-22 11:41 UTC by nktsitas

Adds CloudCommand on top of agent-connection branch

2021-03-30 09:04 UTC, papazach approved these changes

2021-03-30 09:19 UTC, chrikar approved these changes

2021-03-30 09:48 UTC, lvrach requested changes
Minor changes, removal of the `CloudCommand` wrapping message.

2021-03-30 09:48 UTC, lvrach commented on proto/agent/v1/connection.proto
> +}
```suggestion
```

As we discussed, for now, there is no reason to wrap messages sent to the agent. The message type will be embedded in the message topic.

2021-03-30 09:48 UTC, lvrach commented on proto/agent/v1/connection.proto
> +}
```suggestion
```

2021-03-30 10:13 UTC, lvrach commented on proto/agent/v1/connection.proto
> +    string mqtt_broker_addr = 2;
The `mqtt_broker_addr` is no longer neccessery for routing messages inside cloud.
```suggestion
    string mqtt_broker_addr = 2;
```

2021-04-02 09:46 UTC, lvrach approved these changes

2021-04-02 09:48 UTC, merged